/**
 * ForestVPN Cloud SDK API
 *
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@forestvpn.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.cloud.sdk.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessToken 
 * @param tokenType 
 * @param expiresIn 
 */

data class AccessToken (

    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "token_type")
    val tokenType: kotlin.String,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int

)

