/**
 * ForestVPN Cloud SDK API
 *
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@forestvpn.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.cloud.sdk.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 */

data class Profile (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

)

